#!/bin/bash
# PostCompact hook — fires mid-session when context window compacts.
# Writes the compaction summary (already generated by Claude) to a checkpoint file.
# Non-blocking: runs in background, user session continues immediately.

INPUT=$(cat)

SUMMARY=$(echo "$INPUT" | jq -r '.compact_summary // empty')
CWD=$(echo "$INPUT" | jq -r '.cwd // empty')

# Skip if missing required fields
[ -z "$SUMMARY" ] && exit 0
[ -z "$CWD" ] && exit 0

MAIN_WORKTREE=$(git -C "$CWD" worktree list --porcelain 2>/dev/null | awk '/^worktree /{print $2; exit}')
PROJECT=$(basename "${MAIN_WORKTREE:-$CWD}")
TIMESTAMP=$(date +%F-%H%M)
LOG_DIR="$HOME/claude-dev-logs/$PROJECT"

mkdir -p "$LOG_DIR"

cat >> "$LOG_DIR/checkpoints.md" <<EOF

## Checkpoint: $TIMESTAMP
$SUMMARY
---
EOF
